services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: keyboard_cat
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -c 'select * from player_turns;'"]
      start_interval: 1s
      start_period: 1s
      retries: 10
    ports:
      - 5432:5432
    networks:
      - space_battle_network
  game:
    build: .
    volumes:
      - .:/code
    ports:
      - 3000:3000
    networks:
      - space_battle_network
  backend_hx:
    profiles:
      - editor
    build: ../helix_config
    volumes:
      - .:/code
    networks:
      - space_battle_network
  frontend_hx:
    profiles:
      - editor
    build: ../helix_config
    volumes:
      - ../anathema_space_battle:/code/code
      - ../bb_anathema:/code/bb_anathema
    networks:
      - space_battle_network
  frontend:
    profiles:
      - game
    build: ../anathema_space_battle
    volumes:
      - ../anathema_space_battle:/code/game
      - ../bb_anathema:/code/bb_anathema
    networks:
      - space_battle_network
networks:
  space_battle_network:
